from pydantic import BaseModel, Field

class RAGResult(BaseModel):
    content: str = Field(description = "This contains the content returned after the similarity search is done")
    similarity: float = Field(description="This contains the similarity index which lies between 0 to 1")  

class LLMResponse(BaseModel):
    context: str = Field(description="This field contains the context provided to the LLM to generate suitable reponse")
    response: str = Field(description="The response generated by LLM")
